language: python

cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"
  
matrix:
  include:
  - python: 2.7
  - python: 3.4
  - python: 3.5
  - python: 3.6
  - python: 3.6
    arch: arm64
  - python: 3.7
  - python: 3.7
    arch: arm64
  - python: 3.8
  - python: 3.8
    arch: arm64
  - python: 3.8
    services:
    - docker
    env: BUILD_WHEEL=true
  - python: 3.8
    arch: arm64
    services:
    - docker
    env: BUILD_WHEEL=true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - unixodbc-dev
    
install:
if [ $BUILD_WHEEL == true ]; then
  cibuildwheel --output-dir dist
fi

script:
if [ $BUILD_WHEEL == true ]; then
  cibuildwheel --output-dir dist
fi
