language: python
sudo: false
#python:
  #- "2.7"
  #- "3.4"
  #- "3.5"
  #- "3.6"

os: linux

jobs:
  exclude:
      # Exclude the default Python 3.5 build
      - python: 3.5
  include:
   -  os: linux
      name: ARM64-Linux-Py36
      arch: arm64-graviton2
      dist: focal
      virt: vm
      group: edge
      env:
        - MB_PYTHON_VERSION=3.6
        - PLAT=aarch64
        - NP_BUILD_DEP=numpy==1.19.1
        - CYTHON_BUILD_DEP="Cython"
        - DOCKER_IMAGE=quay.io/pypa/manylinux2014_${PLAT}
      script:
        - echo "This stage will just build AArch64 wheel"
      workspaces:
        create:
          name: ws2
          paths:
            - wheelhouse
      after_success:
        - echo "This stage will not upload aarch64 wheel"
   
    - os: linux
      name: amd64-Linux-Py36
      env:
        - MB_PYTHON_VERSION=3.6
        - NP_BUILD_DEP=numpy==1.14.5
        - NP_TEST_DEP=numpy==1.14.5
    - os: linux
      name: 32bit-amd64-Linux-Py36
      env:
        - MB_PYTHON_VERSION=3.6
        - PLAT=i686
        - NP_BUILD_DEP=numpy==1.14.5
        - NP_TEST_DEP=numpy==1.14.5
   
    - stage: Test wheel
    - arch: arm64-graviton2
      name: ARM64-Linux-Py36
      dist: focal
      virt: vm
      group: edge
      env:
        - MB_PYTHON_VERSION=3.6
        - PLAT=aarch64
        - NP_TEST_DEP=numpy==1.19.1
        - CYTHON_BUILD_DEP="Cython"
        - DOCKER_TEST_IMAGE=multibuild/xenial_arm64v8
      workspaces:
        use: ws2
      install:
        - echo "This stage will test and upload the AArch64 wheel"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - unixodbc-dev

install:
  - python setup.py install

script: true
