language: python
sudo: false
#python:
  #- "2.7"
  #- "3.4"
  #- "3.5"
  #- "3.6"
dist: bionic
services: docker
os: linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - unixodbc-dev

jobs:
  exclude:
      # Exclude the default Python 3.5 build
      - python: 3.5
  include:
    - stage: Build and test wheel
      name: ARM64-Linux-Py36
      os: linux
      arch: arm64-graviton2
      dist: focal
      virt: vm
      group: edge
      env:
        - MB_PYTHON_VERSION=3.6
        - PLAT=aarch64
        - NP_BUILD_DEP=numpy==1.19.1
        - CYTHON_BUILD_DEP="Cython"
        - DOCKER_IMAGE=quay.io/pypa/manylinux2014_${PLAT}
      script:
        - echo "This stage will just build AArch64 wheel"
      workspaces:
        create:
          name: ws1
          paths:
            - wheelhouse
      after_success:
        - echo "This stage will not upload aarch64 wheel"
   
    - stage: Test wheel
      name: ARM64-Linux-Py36
      arch: arm64-graviton2
      dist: focal
      virt: vm
      group: edge
      env:
        - MB_PYTHON_VERSION=3.6
        - PLAT=aarch64
        - NP_TEST_DEP=numpy==1.19.1
        - CYTHON_BUILD_DEP="Cython"
        - DOCKER_TEST_IMAGE=multibuild/xenial_arm64v8
      workspaces:
        use: ws1
      install:
        - echo "This stage will test and upload the AArch64 wheel"

install:
  - python setup.py install

script: true
